---
- name: Provision Machine for Linux Kernel Development
  hosts: all
  gather_facts: no
  become: true

  tasks:
    - name: "Get the uname version"
      shell: "uname -r"
      register: uname
      changed_when: false

    - name: Update apt-get repo and cache
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install required packages
      package: 
        state: "present"
        name: "{{ item }}"
      with_items: 
          - libelf-dev
          - build-essential
          - "linux-headers-{{uname.stdout}}"
